# Generated by Django 3.0 on 2019-12-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchWord', models.TextField()),
                ('websiteURL', models.TextField()),
                ('retrieveTime', models.TextField()),
                ('searchResult', models.TextField()),
                ('websiteDescription', models.TextField()),
                ('label', models.TextField()),
            ],
        ),
    ]
