# Generated by Django 3.0 on 2019-12-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='searchID',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='retrieveTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
